# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
import numpy as np
data = np.arange(8)
data=data.reshape(2,4)
data

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [13]:
a=np.arange(8).reshape(2,4)
b=np.arange(9,17).reshape(2,4)

print(a,b)
print(np.vstack((a,b)))


[[0 1 2 3]
 [4 5 6 7]] [[ 9 10 11 12]
 [13 14 15 16]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  1  2  3  9 10 11 12]
 [ 4  5  6  7 13 14 15 16]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [14]:
a=np.arange(8).reshape(2,4)
b=np.arange(9,17).reshape(2,4)

print(a,b)
print(np.hstack((a,b)))


[[0 1 2 3]
 [4 5 6 7]] [[ 9 10 11 12]
 [13 14 15 16]]
[[ 0  1  2  3  9 10 11 12]
 [ 4  5  6  7 13 14 15 16]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [16]:
data=np.arange(80).reshape(10,8)
print(data)
print(data.ravel())

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [17]:
data =np.arange(72).reshape(3,4,6)
print(data)
print(data.ravel())

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]
  [36 37 38 39 40 41]
  [42 43 44 45 46 47]]

 [[48 49 50 51 52 53]
  [54 55 56 57 58 59]
  [60 61 62 63 64 65]
  [66 67 68 69 70 71]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [20]:
data =np.arange(72)
data = data.reshape(3,4,6)
data

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70, 71]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [25]:
a= np.random.rand(5,5)*100

print(np.square(a))

[[ 315.88870132 1903.04696962 1776.4841046  2982.60495352  508.31253362]
 [4501.83527047 5759.2914548  2823.86465318 2703.78155162 8350.39406737]
 [4260.34784814 1081.45390809 3732.7162669    60.76128688 2549.43003735]
 [2079.292105   5632.0179341  6942.95645685 1461.32670743  252.61558559]
 [1600.80471641 5176.71661433 3499.53811606 5146.81007877 9778.92888233]]


## Question:8

### Create 5x6 an array and find the mean?

In [28]:
data = np.random.randint(1,9,size=(5,6))
print(np.mean(data))

4.833333333333333


## Question:9

### Find the standard deviation of the previous array in Q8?

In [29]:
data = np.random.randint(1,9,size=(5,6))
print(np.std(data))

2.2313423961572747


## Question:10

### Find the median of the previous array in Q8?

In [32]:
data = np.random.randint(1,9,size=(5,6))
print(np.median(data))

3.5


## Question:11

### Find the transpose of the previous array in Q8?

In [33]:
data = np.random.randint(1,9,size=(5,6))
print(data)
print(data.transpose())

[[7 6 8 8 3 5]
 [6 7 4 1 8 2]
 [2 4 2 3 7 5]
 [1 6 2 1 5 3]
 [7 1 5 8 6 3]]
[[7 6 2 1 7]
 [6 7 4 6 1]
 [8 4 2 2 5]
 [8 1 3 1 8]
 [3 8 7 5 6]
 [5 2 5 3 3]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [35]:
data = np.random.randint(1,9,size=(4,4))
print(data,np.trace(data))

[[3 2 8 1]
 [4 4 5 7]
 [7 3 8 7]
 [8 3 5 7]] 22


## Question:13

### Find the determinant of the previous array in Q12?

In [36]:
data = np.random.randint(1,9,size=(4,4))
print(np.linalg.det(data))

393.99999999999966


## Question:14

### Find the 5th and 95th percentile of an array?

In [38]:
data = np.arange(100)
print("5th percentile of arr : ",np.percentile(data, 5))
print("95th percentile of arr : ",np.percentile(data, 95))

5th percentile of arr :  4.95
95th percentile of arr :  94.05


## Question:15

### How to find if a given array has any null values?

In [43]:
data = np.identity(3)
data[0,0]=None
print(np.isnan(data))


[[ True False False]
 [False False False]
 [False False False]]
